name: intl_utils
description: intl_utils is a dart library that generates Dart localization code from ARB file. Generated code relies on Intl library.
version: 2.8.8
homepage: https://github.com/localizely/intl_utils

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  analyzer: ^6.8.0
  archive: ^3.6.1
  args: ^2.6.0
  dart_style: ^2.3.7
  http: ">=0.13.0 <2.0.0"
  intl: ">=0.17.0 <0.21.0"
  path: ^1.9.0
  petitparser: ">=4.0.0 <7.0.0"
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^5.0.0
  mockito: ^5.4.4
  test: ^1.25.8
